# Generated by Django 6.0.1 on 2026-01-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_content', models.TextField()),
                ('source', models.CharField(default='System Server', max_length=100)),
                ('compressed_content', models.TextField(blank=True)),
                ('original_size', models.IntegerField(default=0)),
                ('compressed_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
